blank_issues_enabled: false
contact_links:
  - name: GitHub Issues / Support
    url: https://github.com/mattes1007/paradigma-peleo14-homeassistant/issues
    about: Support for this fork. / Hilfe zu diesem Fork.
