name: HACS validation

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-hacs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Validate custom integration repository
        uses: hacs/action@main
        with:
          category: integration
          comment: "false"
